# Generated by Django 5.1.2 on 2024-10-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='---------', max_length=9)),
                ('current_turn', models.CharField(choices=[('X', 'X'), ('O', 'O')], default='X', max_length=1)),
                ('winner', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O'), ('D', 'Draw')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
